common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: stitchfix_production
  password: stitchfix_production

development:
  database: stitchfix_production
  <<: *common

staging:
  database: stitchfix_production
  <<: *common

test:
  database: stitchfix_production_test
  <<: *common

production:
  database: stitchfix_production
  <<: *common

readonly:
  database: stitchfix_production
  <<: *common